const projects = [
  {
    title: "Miesiany Miesiany Kebab",
    industry: "Food & Restaurant industry",
    description: `
      Fullstack application for business from gastronomic industry created with Spring on backend and Angular on frontend. Intended to serve as digital business card to reach more customers, encourage them to stay longer and to solve problems typical for this industry. 

      System provides convenient UI (RWD, multilingual pages, eye-catching colors, customizable by manager paragraphs) and all essential information in one place. Offers a set of marketing tools that enhance brand strength, customer engagement and support business growth - marketing slogans, discount codes, newsletter or gamification systems while placing orders. Ensures real impact on repeat visits and building better relationships with customers.

      Another functionality that distinguishes the system is job board, where manager can add fully customizable job offer with information such as position name, list of Mandatory / Nice to have requirements, employment types or hourly wage gross. Guests can apply to each job offer by fulfilling form with attaching CV in PDF/DOC format. System share possibility to easy candidate selection or download CV attached by candidate.

      Also implemented real-time panels with WebSockets to ensure instant data synchronization on views, which really needs it. Good example can be "Order Status Display" view for in-restaurant screens which show numbers of orders currently being prepared (in gray color) and ready (in green color). Tracking order view is also a view of this type.

      Finally, it is worth mentioning some staff panels - for example work schedule panel which allow to manage shifts in selected month (document can be then displayed or downloaded in PDF format) or payments panel where manager can clearly check all necessary information about payments related to particular employee for any month.
    `,
    images: [
      "/projects/miesiany-miesiany-kebab/logo.png",
      "/projects/miesiany-miesiany-kebab/login1.gif",
      "/projects/miesiany-miesiany-kebab/home1.png",
      "/projects/miesiany-miesiany-kebab/home2.gif",
      "/projects/miesiany-miesiany-kebab/openinghours1.png",
      "/projects/miesiany-miesiany-kebab/openinghours2.gif",
      "/projects/miesiany-miesiany-kebab/menu1.gif",
      "/projects/miesiany-miesiany-kebab/newsletter1.gif",
      "/projects/miesiany-miesiany-kebab/newsletter2.png",
      "/projects/miesiany-miesiany-kebab/newsletter3.png",
      "/projects/miesiany-miesiany-kebab/newsletter4.gif",
      "/projects/miesiany-miesiany-kebab/newsletter5.png",
      "/projects/miesiany-miesiany-kebab/jobs1.gif",
      "/projects/miesiany-miesiany-kebab/jobs2.gif",
      "/projects/miesiany-miesiany-kebab/contact1.png",
      "/projects/miesiany-miesiany-kebab/order1.gif",
      "/projects/miesiany-miesiany-kebab/order2.png",
      "/projects/miesiany-miesiany-kebab/order3.gif",
      "/projects/miesiany-miesiany-kebab/order4.gif",
      "/projects/miesiany-miesiany-kebab/ordermanagement1.gif",
      "/projects/miesiany-miesiany-kebab/orderstatusdisplay1.gif",
      "/projects/miesiany-miesiany-kebab/managerpanel1.gif",
      "/projects/miesiany-miesiany-kebab/employeepanel1.gif",
      "/projects/miesiany-miesiany-kebab/discountcodes1.png",
      "/projects/miesiany-miesiany-kebab/discountcodes2.gif",
      "/projects/miesiany-miesiany-kebab/employeemanagement1.png",
      "/projects/miesiany-miesiany-kebab/workschedule1.gif",
      "/projects/miesiany-miesiany-kebab/payments1.gif",
    ],

    features: [
      "Session-based authentication system, taking into data security - implemented storing passwords encrypted with the bcrypt algorithm in database.",
      "Well-tailored UI with eye-catching colors.",
      "Responsive Web Design to improve accessibility of UI at all types of devices.",
      "Multilingual pages (Polish or English),",
      "Multilingual validation for all forms. Validation messages are sent by backend in appropriate language specified in request header.",
      "Integration with TomTom Map API to add map with pointer making locating restaurant much easier to potential customers.",
      "Bash script, which starts PostgreSQL database, backend and frontend with one command.",
      "Possibility to follow application flow and diagnose potential issues by accessing informational, warning and error logs in console.",
      'Possibility to display Home Page - "First contact section", which clients see firstly after navigating to root URL. Had to be designed in the best way from marketing perspective - there should be many information, that can encourage potential customer to place order. Contains marketing slogans, certificates, guarantees, acknowledgments and a map with pointer.',
      "Possibility to display highlighted with proper color easy to customize by manager opening hours of restaurant on each day.",
      "Possibility to display Menu of the restaurant divided to three sections: Meals, Addons and Beverages. Customer can learn about each menu item details like name, price, capacity or ingredients. Entire section is customizable by manager - can add, update and remove each type of item. Items in each section are sorted by name.",
      "Possibility to display Contact details - phoone number, email address, nicknames at social media and map with location pointer. Contact data is customizable by manager.",
      "Job board, which enable manager to add fully customizable job offers with information such as position name, description, list of Mandatory / Nice to have requirementslist of employment types or hourly wage gross. Website guests interested in work for restaurant can apply to each job offer by fulfilling form (with attaching a CV in PDF/DOC format). System also share possibility to display all candidates, which applied to job offer, remove those who do not fit the position or display/download CV attached by desired candidate.",
      "Promotions for Meals, Beverages and Addons possible to see in proper view of website by all customers. If some menu position is already added to certain promotion, customers can see price change in menu section or while placing order. All promotions are customizable by manager - can add, update and delete promotions.",
      "Multilingual promotions newsletter with email verification implemented with usage of Observer design pattern. Each customer has possibility to sign up to newsletter and choose preffered language of email messages (Polish or English). When some promotion is added, then email is sent to all verified subscribers. From technical perspective some methods related to feature are asynchronous to enhance application preformance. System offers possibility to unsubscribe newsletter at any time.",
      "Discount codes with which customers can reduce price of order - each code has its expiration date and number of remaining uses. Automatically generated and sending to customers, who provide their email address during placing order process - either after every 10 orders or when the order total price exceeds 100 PLN. Manager can add, update and delete discount codes (allowing for manual distribution as well). ",
      "Possibility to place order by customers in easy and concise way - each menu position can be selected and added to order, then partially customized (by choosing size, meat, sauce, quantity or capacity). After adding item, customer may continue adding more items, proceed to the next step or come back later (all order details are saved in local storage). Next step is choosing preferred delivery method: pickup at the restaurant or home delivery. Depending on the choice dedicated panel is shown to collect the necessary information. Finally, customer has the option to leave additional comments and enter a discount code to receive a price reduction. Managers and employees can add, update and delete orders.",
      "Real-time panels related to orders (order display, order management and track order) implemented with usage of WebSockets for instant data synchronization.",
      "Track order panel, where customers can easily monitor status of their order in real time. Here they can find information such as order id (number of order displayed on the screen in restaurant), total price, delivery address (if home delivery method was selected), payment methods, ordered items details and current order status. Customers can access this panel for up to two hours after the last update to their order.",
      "Real-time order status display for in-restaurant screen, which shows numbers of orders currently being prepared (in gray color) and those, that are ready (in green color). This provides clear information to customers waiting in the restaurant, improving communication and overall experience.",
      "Work schedule panel which allows managers to assign shifts for all employees for a selected month and year. All employees can display and then download a printable PDF document that clearly displays the shift schedule.",
      "Employee management panel where manager can add, update or remove employees.",
      "Employee and manager panels which allow authenticated users to view their current contact information and employment details. Each panel includes an actions section with buttons that provide functions available to the particular account type (employee or manager). Both employees and managers can also update their email address and password.",
      "Payments panel where manager can clearly check all necessary information about payments related to particular employee for any month: personal data, job, employment type, current hourly wage gross, hourly wage gross in chosen period, working hours in chosen period, student status and total payment amount.",
      "Rate limiting applied to public API endpoints to protect system from excessive or malicious traffic.",
    ],
    technologies: [
      "Java 21",
      "TypeScript",
      "Spring",
      "Angular 18",
      "Bootstrap",
      "Hibernate",
      "Thymeleaf",
      "Maven",
      "JUnit",
      "Mockito",
      "PostgreSQL",
      "HTML",
      "SCSS",
      "Docker",
      "Bash",
    ],
    url: "miesiany-miesiany-kebab",
    repoUrl: "https://github.com/P4ZD4N/miesiany-miesiany-kebab",
    completed: false,
  },
  {
    title: "Bibliotheca Chudyana",
    industry: "Library industry",
    description: `
      Backend application (Spring) created to facilitate Library / Bookstore business management and to make interaction with potential customers more effective. A subtle dark-themed interface was also implemented to ensure a better user experience.

      Idea behind the application is obvious - digitization process significantly simplifies the provision of library services what can lead to increases in revenues and customer loyalty. Because of easy access to bookstore resources online, customers can browse books whenever they want and search desired ones by filtering to familiarise with book collection without leaving home. There are also carts and wishlists feature available, allowing even more to better reconsider order and return to completing it at any time.

      To enhance user experience and make using system more enjoyable application includes dedicated satisfaction-oriented features. First worth to mention are discounts, which can be tracked by each customer in appropriate section on website. There was also rating system implemented, which gives customers possibility to share thoughts about book with others by leaving review or rating. Additionally system offers special views where customers can display their order statuses, most popular book categories or newly added books.

      Staff of bookstore (employees and managers) have access to management panels through user profile. They can easily manage among others books, users, orders or discount.
    `,
    images: [
      "/projects/bibliotheca-chudyana/logo.png",
      "/projects/bibliotheca-chudyana/1.png",
      "/projects/bibliotheca-chudyana/2.png",
      "/projects/bibliotheca-chudyana/3.png",
      "/projects/bibliotheca-chudyana/4.png",
      "/projects/bibliotheca-chudyana/5.png",
      "/projects/bibliotheca-chudyana/6.png",
      "/projects/bibliotheca-chudyana/7.png",
      "/projects/bibliotheca-chudyana/8.png",
      "/projects/bibliotheca-chudyana/9.png",
      "/projects/bibliotheca-chudyana/10.png",
      "/projects/bibliotheca-chudyana/11.png",
      "/projects/bibliotheca-chudyana/12.png",
      "/projects/bibliotheca-chudyana/13.png",
      "/projects/bibliotheca-chudyana/14.png",
      "/projects/bibliotheca-chudyana/15.png",
      "/projects/bibliotheca-chudyana/16.png",
      "/projects/bibliotheca-chudyana/17.png",
      "/projects/bibliotheca-chudyana/18.png",
      "/projects/bibliotheca-chudyana/19.png",
      "/projects/bibliotheca-chudyana/21.png",
      "/projects/bibliotheca-chudyana/22.png",
    ],
    features: [
      "Secure user registration and authentication system, which use bcrypt encryption algorithm to ensure data protection.",
      "Ability for users to change the email address and password.",
      "Browsing full catalog of books and searching them based on selected criteria and keywords.",
      "Adding new books and updating existing ones by users with appropriate roles.",
      "Viewing most popular categories and newly added books (books, which were added to library in past 7 days)",
      "Viewing available discounts, with option to add new or update existing by users with appropriate roles.",
      "Adding, updating or deleting. review or rating for each book by authenticated users.",
      "Viewing and managing own profile for authenticated users.",
      "Adding or removing books from wishlist.",
      "Adding or removing books from cart.",
      "Placing orders using items from cart.",
      "Admin panel enabling administrators to manage books, users, orders, reviews, and discounts.",
      "Manager panel enabling managers to manage books, orders, reviews and discounts.",
      "Employee panel enabling employees to manage books and orders.",
    ],
    technologies: [
      "Java",
      "Spring",
      "Hibernate",
      "Thymeleaf",
      "Maven",
      "JUnit",
      "Mockito",
      "MySQL",
      "JavaScript",
      "HTML",
      "SCSS",
      "Docker",
    ],
    url: "bibliotheca-chudyana",
    repoUrl: "https://github.com/P4ZD4N/bibliotheca-chudyana",
    completed: true,
  },
  {
    title: "GloboGym",
    industry: "Fitness & Health industry",
    description: `Robust desktop application developed with usage of JavaFX designed to support major of operations of a modern fitness club. System has been carefully architected to address a wide range of business scenarios for both customers and employees. Development process involved deep research, precise modeling of use cases and rigorous attention to detail to ensure system reliability and intuitive UX. It covers all important business processes - user registration, membership management, scheduling, payments, role-based access and so on. Project demonstrates not only strong technical skills (Java, JavaFX, UI/UX design, OOP) but also ability to analyze real business requirements and translate them into robust, user-friendly solutions. It automates key operations, reduces human errors and enhances user experience with an intuitive, responsive interface. Also shows, how thoughtful system design can support digital transformation and improve efficiency of business in fitness industry.`,
    images: [
      "/projects/globogym/logo.png",
      "/projects/globogym/1.png",
      "/projects/globogym/2.png",
      "/projects/globogym/3.png",
      "/projects/globogym/4.png",
      "/projects/globogym/5.png",
      "/projects/globogym/6.png",
      "/projects/globogym/7.png",
      "/projects/globogym/8.png",
      "/projects/globogym/9.png",
      "/projects/globogym/10.png",
      "/projects/globogym/11.png",
      "/projects/globogym/12.png",
      "/projects/globogym/13.png",
      "/projects/globogym/14.png",
      "/projects/globogym/15.png",
      "/projects/globogym/16.png",
      "/projects/globogym/17.png",
      "/projects/globogym/18.png",
      "/projects/globogym/19.png",
      "/projects/globogym/20.png",
      "/projects/globogym/21.png",
    ],
    features: [
      "All user interactions and data changes are saved to file and visible after restarting app due to used serialization mechanisms.",
      "All input fields across the application are validated to ensure data integrity.",
      "Registration. Both club member and coach account can be created. Coach accounts require manual approval by authorized employee.",
      "Authentication. Mechanism to login to user account after registration.",
      "Real-time access to gym opening hours and open/closed status based on current time and date.",
      "Personalized user dashboard with possibility to update personal data (with setting up specializations on coach accounts) and upload avatar.",
      "Interactive calendar-based schedule view with highlighted classes and other events on appropriate days and times.",
      "Possibility to see some statistics related to account, which is currently authenticated.",
      "Payments module allowing users to deposit money, follow up their account balance and view transaction history.",
      "Membership management view allowing to purchase/renew membership and visualize appearance of their membership card.",
      "Intelligent class booking system for club members and coaches with validation (by checking active membership, availability, future dates or duplicates).",
      "Possibility to add classes to schedule by coaches with active membership, employees and managers.",
      "Possibility to add other events to schedule by employees and managers.",
      "Administration panels for employees and managers.",
    ],
    technologies: ["Java", "JavaFX", "Lombok", "Maven", "CSS"],
    url: "globogym",
    repoUrl: "https://github.com/P4ZD4N/globogym",
    completed: true,
  },
  {
    title: "Instalatorstwo elektryczne",
    industry: "Electrical industry",
    description:
      "Comprehensive marketing strategy for a client operating in the electrical industry. My work included: lightweight website, full branding package (custom logo design, vehicle decals for company car, branded t-shirts and jackets for staff, promotional banners highlighting new services and large banner installed on a pole near office), boosting online presence by setting up and optimizing Facebook business page and Google Maps listing to improve local discoverability.",
    images: [
      "/projects/instalatorstwo-elektryczne/logo.png",
      "/projects/instalatorstwo-elektryczne/banner.png",
      "/projects/instalatorstwo-elektryczne/1.png",
      "/projects/instalatorstwo-elektryczne/2.png",
      "/projects/instalatorstwo-elektryczne/3.png",
      "/projects/instalatorstwo-elektryczne/4.png",
      "/projects/instalatorstwo-elektryczne/5.png",
      "/projects/instalatorstwo-elektryczne/6.png",
      "/projects/instalatorstwo-elektryczne/7.png",
      "/projects/instalatorstwo-elektryczne/1.gif",
    ],
    features: [
      "Designed and developed lightweight website, which is intended to serve as a business card. Created using HTML, SCSS, Bootstrap and vanilla JavaScript. Chose framework-free implementation to reduce overhead and better align with long-term maintainability and budget constraints. One of the most important features is integration with Google Analytics for tracking website traffic in easy way.",
      "Created full branding package including custom logo design, vehicle decals for company car, branded t-shirts and jackets for staff, promotional banners highlighting new services and large banner installed on a pole near office.",
      "Boosted online presence by setting up and optimizing Facebook business page and Google Maps listing to improve local discoverability.",
    ],
    technologies: ["JavaScript", "HTML", "SCSS", "Bootstrap"],
    url: "instalatorstwo-elektryczne",
    repoUrl: "https://github.com/P4ZD4N/instalatorstwo-elektryczne",
    liveUrl: "https://marcinchudy.com",
    completed: true,
  },
  {
    title: "Wiktor Chudy",
    industry: "Personal website and blog",
    description:
      "My personal website combined with blog is a place where others can discover who I am both professionally and personally. It brings detailed insights into my projects, work expierience, education and the skills I have developed over time. Beyond being a digital portfolio, it's also space where I share knowledge, reflect on my experiences and document my growth. Intended for anyone who wants to get to know me better, what I care about and what I’m capable of.",
    images: [],
    features: [
      "Home page - quick introduction and all essential information in one place. Section includes tech carousel showcasing my core technical skills, project cards highlighting my most important projects, article cards featuring my three most recent articles and contact section with my social links and contact data.",
      "Work page - place where you can discover detailed insights into my projects including image galleries, full descriptions, features lists and technologies lists.",
      "About me page - section where you can get to know me better. Contains detailed information about me both as a professional and as a person.",
      "Articles page - browse all of my published articles and filter them by category to find topics that interest you.",
      "Contact page - get in touch with me directly. Here you will find my contact details and social media links, making it easy to reach out.",
    ],
    technologies: [
      "TypeScript",
      "React",
      "Next.js 15",
      "HTML",
      "CSS",
      "Tailwind",
    ],
    url: "wiktor-chudy",
    repoUrl: "https://github.com/P4ZD4N/wiktor-chudy",
    liveUrl: "https://wiktorchudy.me",
    completed: false,
  },
  {
    title: "Baloney",
    industry: "Social networking",
    description:
      "Full-stack app intended to share memories with other people, who uses it. During development I am mainly responsible for backend development. It is collaborative app, which I create with my friend. During development we do code reviews and exchange our ideas to solve problems more effectively.",
    images: [],
    features: [
      "User registration and authentication system implemented with JWT for token-based sessions and bcrypt for secure password hashing.",
      "Support for uploading user avatars integrated with AWS S3 for file storage.",
      "Email verification via JavaMailSender, using OTP for confirmation.",
      "Forgot password feature, allowing users to reset forgotten passwords through JavaMailSender.",
    ],
    technologies: [
      "Java 21",
      "Spring Boot",
      "Spring Security",
      "Spring Data",
      "Hibernate",
      "Thymeleaf",
      "Maven",
      "PostgreSQL",
      "HTML",
      "Docker",
      "AWS S3",
      "AWS IAM",
    ],
    url: "baloney",
    repoUrl: "https://github.com/surferhand",
    completed: false,
  },
  {
    title: "DBee",
    industry: "Data storage systems",
    description:
      "Authorial Relational Database Management System (RDBMS) created with C++20. App is intended to serve as a storage, which enable to manage data with query language similar to SQL. User can create and manage multiple databases within the entire system. While building this system, I learned how relational databases work under the hood - including how they handle schemas, data types, constraints, and foreign keys. This helped me better understand how higher-level tools work and how to connect application development with how databases are actually built.",
    images: [],
    features: [
      "Possibility to manage multiple independent databases in one environment.",
      "Support for creating and managing tables with the ability to define columns with precisely defined data types: INTEGER, FLOAT or TEXT.",
      "Possibility to add important constraints on columns to ensure data integrity: PRIMARY KEY, FOREIGN KEY, UNIQUE or NOT NULL.",
      "Parser, which has ability to interpret queries written in a SQL-like syntax and execute proper operations based on entered query.",
      "Possibility to save and read RDBMS data from file. Enable to restore the entire RDBMS structure including databases, tables, columns, constraints and data.",
    ],
    technologies: ["C++20", "CMake"],
    url: "dbee",
    repoUrl: "https://github.com/P4ZD4N/dbee",
    completed: true,
  },
  {
    title: "Area intruders",
    industry: "Game development",
    description:
      "Game based on classic and iconic Space Invaders - arcade game, in which player controls the ship trying to shoot down approaching enemies. The main goal of creating such project was to apply more advanced aspects of Java language in practice. To create it, I used, among others, multithreading mechanisms, lambdas or streams. User interface was implemented with usage of Swing and AWT libraries, which provide powerful tools for building GUI and managing events within game. ",
    images: [
      "/projects/area-intruders/1.png",
      "/projects/area-intruders/2.png",
      "/projects/area-intruders/3.png",
      "/projects/area-intruders/4.png",
      "/projects/area-intruders/5.png",
      "/projects/area-intruders/6.png",
      "/projects/area-intruders/1.gif",
    ],
    features: [
      "Main menu, in which user can enter nickname, choose ship appearance, display instructions, settings and top 10 scores.",
      "Player can control ship using arrow keys on the keyboard or special buttons in the window.",
      "Player can shoot using spacebar or special button in the window.",
      "Player can pause game.",
      "Player can end game at any time and be included in the top 10 results, if he has achieved the appropriate number of points.",
      "Player has a lot of setting options including: default difficulty levels (easy, normal, hard), game modes (normal, disco, mirror) and custom settings (enemy rows, enemy columns, enemy rows falling time). ",
      "Player earn points for hitting an enemy. Number of points depends on the selected difficulty level and game mode (possibly on player's custom settings).",
      "Scores are saved to the file, based on which the top 10 scores is prepared.",
      "Game offers the option of replaying game on previous settings after losing or finishing the game.",
    ],
    technologies: ["Java", "Swing", "AWT"],
    url: "area-intruders",
    repoUrl: "https://github.com/P4ZD4N/area-intruders",
    completed: true,
  },
  {
    title: "Distributed Averaging System",
    industry: "Networking",
    description:
      "Distributed Averaging System is app that operates in two modes: master and slave. The purpose of the application is to collect numerical data from various instances of the program and calculate the average of these numbers. The application uses the UDP communication protocol to transfer data between devices in the local network.",
    images: [
      "/projects/distributed-averaging-system/1.gif",
      "/projects/distributed-averaging-system/2.gif",
      "/projects/distributed-averaging-system/3.gif",
      "/projects/distributed-averaging-system/4.gif",
      "/projects/distributed-averaging-system/5.png",
    ],
    features: [],
    technologies: ["Java 8"],
    url: "distributed-computing-system",
    repoUrl: "https://github.com/P4ZD4N/distributed-averaging-system",
    completed: true,
  },
  {
    title: "Centralized Computing System",
    industry: "Networking",
    description:
      "Java-based server application created to facilitate the detection of its service in a local network, perform arithmetic operations for connected clients and provide statistical reports on its activity. The application operates using both the UDP and TCP protocols to handle different functionalities. The goal of project is to create a robust and efficient server capable of managing multiple clients simultaneously and providing real-time statistics about various operations.",
    images: [
      "/projects/centralized-computing-system/1.gif",
      "/projects/centralized-computing-system/2.png",
      "/projects/centralized-computing-system/3.png",
      "/projects/centralized-computing-system/4.png",
      "/projects/centralized-computing-system/5.png",
      "/projects/centralized-computing-system/6.png",
      "/projects/centralized-computing-system/7.png",
      "/projects/centralized-computing-system/8.png",
      "/projects/centralized-computing-system/9.png",
    ],
    features: [],
    technologies: ["Java 8"],
    url: "centralized-computing-system",
    repoUrl: "https://github.com/P4ZD4N/centralized-computing-system",
    completed: true,
  },
];

export default projects;
